export const SKILLS_ICONS: Record<string, { iconName: string }> = {
	"Ant Design": { iconName: "logos:ant-design" },
	Astro: { iconName: "logos:astro" },
	AWS: { iconName: "skill-icons:aws-dark" },
	"Bash Script": { iconName: "skill-icons:bash-dark" },
	BigQuery: { iconName: "bigquery" },
	BloomRPC: { iconName: "bloomrpc" },
	Bootstrap: { iconName: "skill-icons:bootstrap" },
	Cloudflare: { iconName: "skill-icons:cloudflare-dark" },
	"Cloudflare Page": { iconName: "skill-icons:cloudflare-dark" },
	Confluence: { iconName: "logos:confluence" },
	"CSS Modules": { iconName: "simple-icons:cssmodules" },
	CSS: { iconName: "skill-icons:css" },
	CLI: { iconName: "mdi:terminal" },
	"Docker Compose": { iconName: "skill-icons:docker" },
	Docker: { iconName: "skill-icons:docker" },
	EC2: { iconName: "logos:aws-ec2" },
	EKS: { iconName: "logos:aws-eks" },
	Envoy: { iconName: "simple-icons:envoyproxy" },
	Figma: { iconName: "skill-icons:figma-dark" },
	Git: { iconName: "skill-icons:git" },
	"GitHub Actions": { iconName: "skill-icons:github-dark" },
	"GitLab CI": { iconName: "skill-icons:gitlab-dark" },
	"GitLab CI/CD": { iconName: "skill-icons:gitlab-dark" },
	Golang: { iconName: "skill-icons:golang" },
	"Google Analytics": { iconName: "logos:google-analytics" },
	"Google Cloud": { iconName: "skill-icons:gcp-dark" },
	gRPC: { iconName: "logos:grpc" },
	Heroku: { iconName: "skill-icons:heroku" },
	HTML: { iconName: "skill-icons:html" },
	Helm: { iconName: "logos:helm" },
	JavaScript: { iconName: "skill-icons:javascript" },
	Jira: { iconName: "logos:jira" },
	Kubernetes: { iconName: "skill-icons:kubernetes" },
	Linux: { iconName: "logos:linux-tux" },
	Lens: { iconName: "lens" },
	Less: { iconName: "logos:less" },
	MacOS: { iconName: "macos" },
	"Material UI": { iconName: "skill-icons:materialui-dark" },
	MongoDB: { iconName: "skill-icons:mongodb" },
	Markdown: { iconName: "skill-icons:markdown-dark" },
	MDX: { iconName: "logos:mdx" },
	MySQL: { iconName: "skill-icons:mysql-dark" },
	Netlify: { iconName: "skill-icons:netlify-dark" },
	"Next.js": { iconName: "skill-icons:nextjs-light" },
	"Node.js": { iconName: "skill-icons:nodejs-dark" },
	"Open Graph": { iconName: "logos:open-graph" },
	Postman: { iconName: "skill-icons:postman" },
	Playwright: { iconName: "logos:playwright" },
	"Protocol Buffers": { iconName: "protobuf" },
	"React Hook Form": { iconName: "react-hook-form" },
	"Radix UI": { iconName: "simple-icons:radixui" },
	React: { iconName: "skill-icons:react-dark" },
	Redux: { iconName: "skill-icons:redux" },
	Regex: { iconName: "skill-icons:regex-dark" },
	"Ruby on Rails": { iconName: "skill-icons:rails" },
	SASS: { iconName: "skill-icons:sass" },
	Selenium: { iconName: "skill-icons:selenium" },
	Slack: { iconName: "logos:slack-icon" },
	"shadcn/ui": { iconName: "simple-icons:shadcnui" },
	"Styled Components": { iconName: "skill-icons:styledcomponents" },
	"Tailwind CSS": { iconName: "skill-icons:tailwindcss-dark" },
	Tailwind: { iconName: "skill-icons:tailwindcss-dark" },
	Terraform: { iconName: "skill-icons:terraform-light" },
	TypeScript: { iconName: "skill-icons:typescript" },
	Vercel: { iconName: "skill-icons:vercel-dark" },
	Windows: { iconName: "logos:microsoft-windows-icon" },
	Zod: { iconName: "logos:zod" },
};
